Fix instant rain saturation
firedrakeproject/gusto pull request #354
Opened 2023-03-07 13:48 UTC by nhartney

This allows the saturation curve for InstantRain to be a function of depth, or a constant in time. If it is a function, the argument `saturation_variable` must be passed to InstantRain.

2023-03-07 13:54 UTC, jshipton commented on integration-tests/physics/test_instant_rain.py
> +    saturation = Function(VD).assign(0.5)
This shouldn't be necessary - it should also work when `saturation` is not a function.

2023-03-07 13:55 UTC, jshipton commented on gusto/physics.py
> +            if self.saturation_variable == "depth":
I would prefer to use the field name rather than "depth" - then you can assert that the string is in the list of field names.

2023-03-07 13:56 UTC, jshipton commented on gusto/physics.py
> +                self.sat_func = Function(Vvar_space)
would prefer not to abbreviate too much - so `saturation_function` instead of `sat_func`

2023-03-07 19:36 UTC, jshipton commented on integration-tests/physics/test_instant_rain.py
> +    saturation = Function(VD).assign(0.5)
That depends on what the error was...

2023-03-14 12:13 UTC, jshipton requested changes
1. Some tidying and renaming required: saturation curve can be an expression or a function - docstring needs to be updated, `variable` should be renamed, don't store things in `self` that aren't used.
2. Test should check both cases for saturation curve.

2023-03-15 16:15 UTC, nhartney commented
Thanks Jemma!
In terms of testing, the moist convective test based on Williamson 5 (which isn't working yet but hopefully will be soon!) will use a saturation function that varies with height. The forced advection test uses `InstantRain`and has a space-dependent saturation function, and this instant rain test has a saturation function that is a `Constant`. In other words, between those two and the new moist convective test we will be testing three types of saturation curve. Do you think, then, that it is alright to have this test test only the `Constant` case? I think including a height-varying saturation curve here would just be a repeat of the moist convective test.

2023-03-15 21:29 UTC, jshipton commented on gusto/physics.py
> +            saturation_curve (ufl.Expr or :class: `function`): the saturation
Should also note that this argument is optional

2023-03-15 21:30 UTC, jshipton commented on gusto/physics.py
> +                function, above which excess moisture is converted. Can be
is it possible to rephrase without using the word "function" or "expression" - just to avoid confusion with the type of the argument...

2023-03-15 21:31 UTC, jshipton commented on gusto/physics.py
> +                time. This field must be one of the equation variables.
"prognostic fields" instead of "variables"

2023-03-15 21:32 UTC, jshipton commented on gusto/physics.py
> +            self.saturation_function = self.saturation_curve
is `self.saturation_curve` ever used? I'm not sure it needs to be stored in `self`.

2023-03-15 21:38 UTC, jshipton reviewed
Some very minor comments on doc strings.

I think I'm still a bit confused by the logic... is it nicer to get rid of `self.saturation_function` and just have `self.saturation_curve`?

2023-03-15 21:39 UTC, jshipton commented
> Thanks Jemma!
> In terms of testing, the moist convective test based on Williamson 5 (which isn't working yet but hopefully will be soon!) will use a saturation function that varies with height. The forced advection test uses `InstantRain`and has a space-dependent saturation function, and this instant rain test has a saturation function that is a `Constant`. In other words, between those two and the new moist convective test we will be testing three types of saturation curve. Do you think, then, that it is alright to have this test test only the `Constant` case? I think including a height-varying saturation curve here would just be a repeat of the moist convective test.

Yes, I think you're right.

2023-04-06 13:20 UTC, jshipton commented on gusto/physics.py
> +            saturation_curve (ufl.Expr or :class: `function`, optional): the
this isn't optional!

2023-04-06 13:26 UTC, jshipton commented on gusto/physics.py
> +            self.saturation_curve = saturation_curve
you need to assert that the saturation_curve is a UFL expression

2023-04-11 08:39 UTC, jshipton approved these changes
looks much tidier now - thanks!

2023-04-11 08:39 UTC, merged