Tracer conservative transport
firedrakeproject/gusto pull request #469
Opened 2023-12-19 02:46 UTC by ta440

Begin the conservative transport project!

2024-03-18 08:17 UTC, tommbendall requested changes
Thanks so much Tim. I think this looks really good and it's very exciting to have this working.

I've got two very small requests. I think it would also be helpful to have @atb1995 look over the changes to time discretisation to ensure that he's happy

2024-03-18 10:00 UTC, ta440 commented on gusto/equations.py
> +        if Vu.extruded:
Oops, this was accidentally left in from trying to find the reason for the failing tests.

2024-03-18 13:19 UTC, ta440 commented on gusto/transport_methods.py
> +            tracer = self.equation.active_tracers[tracer_idx]
These two lines have been replaced with: `tracer = next(x for x in self.equation.active_tracers if x.name == variable)`.

2024-03-19 14:06 UTC, atb1995 reviewed
Looks good! Just a couple of minor comments

2024-03-19 15:57 UTC, tommbendall submitted a review, later dismissed
Thanks Tim, this is fantastic!

2024-03-19 16:40 UTC, merged