Coriolis linear solver
firedrakeproject/gusto pull request #539
Opened 2024-08-16 14:16 UTC by Witt-D

Adding the Coriolis term to be inside the linear solvers

2024-08-16 14:22 UTC, tommbendall requested changes

2024-08-16 14:22 UTC, tommbendall commented on gusto/solvers/linear_solvers.py
> +        if equations.parameters.coriolis is not None:
```suggestion
        if equations.parameters.Omega is not None:
```

2024-08-16 14:22 UTC, tommbendall commented on gusto/solvers/linear_solvers.py
> +        if self.prescribed_fields('coriolis'):
```suggestion
        if 'coriolis' in self.prescribed_fields._field_names:
```

2024-08-16 14:22 UTC, tommbendall commented on gusto/solvers/linear_solvers.py
> +        if self.prescribed_fields('coriolis'):
```suggestion
        if 'coriolis' in self.prescribed_fields._field_names:
```

2024-08-16 14:23 UTC, tommbendall commented on gusto/solvers/linear_solvers.py
> +            + dl*dot(u, n)*(ds_tbp + ds_vp))
Could you revert this bracket change?

2024-08-16 14:23 UTC, tommbendall commented on gusto/solvers/linear_solvers.py
> +            + beta_d * phi * Dbar * div(u) * dx)
and also this bracket change?

2024-08-19 13:30 UTC, jshipton approved these changes
great - thanks @Witt-D !

2024-08-19 13:31 UTC, merged